//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeYourPhone.Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneCondition
    {
        public PhoneCondition()
        {
            this.Phones = new HashSet<Phone>();
        }
    
        public int ID { get; set; }
        public string Condition { get; set; }
    
        public virtual ICollection<Phone> Phones { get; set; }
    }
}
