//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeYourPhone.Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone
    {
        public Phone()
        {
            this.PhoneStatusHistories = new HashSet<PhoneStatusHistory>();
        }
    
        public int Id { get; set; }
        public Nullable<int> QuoteId { get; set; }
        public int PhoneMakeId { get; set; }
        public int PhoneModelId { get; set; }
        public int PhoneConditionId { get; set; }
        public Nullable<decimal> PurchaseAmount { get; set; }
        public int PhoneStatusId { get; set; }
        public string IMEI { get; set; }
        public Nullable<decimal> SaleAmount { get; set; }
        public string PhoneChecklist { get; set; }
        public string PhoneNotes { get; set; }
        public string PhoneDescription { get; set; }
    
        public virtual PhoneCondition PhoneCondition { get; set; }
        public virtual PhoneMake PhoneMake { get; set; }
        public virtual PhoneModel PhoneModel { get; set; }
        public virtual PhoneStatu PhoneStatu { get; set; }
        public virtual Quote Quote { get; set; }
        public virtual ICollection<PhoneStatusHistory> PhoneStatusHistories { get; set; }
    }
}
