//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeYourPhone.Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote
    {
        public Quote()
        {
            this.Phones = new HashSet<Phone>();
            this.QuoteStatusHistories = new HashSet<QuoteStatusHistory>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public int QuoteStatusId { get; set; }
        public Nullable<System.DateTime> QuoteFinalisedDate { get; set; }
        public Nullable<System.DateTime> QuoteExpiryDate { get; set; }
        public string QuoteReferenceId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> PostageMethodId { get; set; }
        public bool AgreedToTerms { get; set; }
        public string Notes { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<Phone> Phones { get; set; }
        public virtual QuoteStatus QuoteStatus { get; set; }
        public virtual PostageMethod PostageMethod { get; set; }
        public virtual ICollection<QuoteStatusHistory> QuoteStatusHistories { get; set; }
    }
}
