//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeYourPhone.Core.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NavexaMobileEntities : DbContext
    {
        public NavexaMobileEntities()
            : base("name=NavexaMobileEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<PaymentDetail> PaymentDetails { get; set; }
        public virtual DbSet<PaymentType> PaymentTypes { get; set; }
        public virtual DbSet<PhoneCondition> PhoneConditions { get; set; }
        public virtual DbSet<PhoneConditionPrice> PhoneConditionPrices { get; set; }
        public virtual DbSet<PhoneMake> PhoneMakes { get; set; }
        public virtual DbSet<PhoneModel> PhoneModels { get; set; }
        public virtual DbSet<Quote> Quotes { get; set; }
        public virtual DbSet<QuoteStatus> QuoteStatus1 { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<Phone> Phones { get; set; }
        public virtual DbSet<PhoneStatu> PhoneStatus { get; set; }
        public virtual DbSet<PostageMethod> PostageMethods { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<PhoneStatusHistory> PhoneStatusHistories { get; set; }
        public virtual DbSet<QuoteStatusHistory> QuoteStatusHistories { get; set; }
        public virtual DbSet<Configuration> Configurations { get; set; }
    }
}
