//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeYourPhone.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDetail
    {
        public int ID { get; set; }
        public int PaymentTypeId { get; set; }
        public string BSB { get; set; }
        public string AccountNumber { get; set; }
        public string PaypalEmail { get; set; }
    
        public virtual PaymentType PaymentType { get; set; }
    }
}
