//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeYourPhone.Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneConditionPrice
    {
        public int ID { get; set; }
        public int PhoneModelId { get; set; }
        public int PhoneConditionId { get; set; }
        public decimal OfferAmount { get; set; }
    
        public virtual PhoneCondition PhoneCondition { get; set; }
    }
}
